// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqxplxkiuhhggvgsbsfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxeHBseGtpdWhoZ2d2Z3Nic2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjE0NDcsImV4cCI6MjA2MjUzNzQ0N30.MmW6DQcL1l3gCsbUdc656jd6ld9Nn1jy9VlZ4oYJzWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);